blank_issues_enabled: false

contact_links:
  - name: Community Support
    url: https://github.com/Jarmos-san/dotfiles/discussions
    about: Please ask and answer questions here.

  - name: Report Issues and/or Bugs
    url: https://github.com/Jarmos-san/dotfiles/issues
    about: Please report bugs & other issues here.

  - name: Security Policy
    url: https://github.com/Jarmos-san/dotfiles/security/policy
    about:
      Refer to the Security Policy to report security vulnerabilities or if you
      would like to know about how your personal information is used.
